[package]
name = "rarity"
version = "1.2.4"
authors = ["Miezhiko"]
repository = "https://github.com/Miezhiko/Rarity"
readme = "README.md"
keywords = ["discord", "bot"]
edition = "2021"
description = "Rarity discord bot"
license = "QUADROBER"
rust-version = "1.80.0"

[features]
default = []

[dependencies]
twilight-http           = { git = "https://github.com/twilight-rs/twilight", branch = "main" }
twilight-gateway        = { git = "https://github.com/twilight-rs/twilight", branch = "main" }
twilight-cache-inmemory = { git = "https://github.com/twilight-rs/twilight", branch = "main" }
twilight-model          = { git = "https://github.com/twilight-rs/twilight", branch = "main" }

anyhow = "*"
tracing = "*"
tracing-subscriber = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml_bw = "*"
serde_dhall = "*"
regex = "*"
rand = "*"
smallvec = "*"
async-recursion = "*"
feed-rs = "*"
tiktoken-rs = "*"
encoding_rs = "*"
base64 = "*"

[dependencies.rustls]
version = "*"
features = ["ring"]

[dependencies.twilight-util]
git = "https://github.com/twilight-rs/twilight"
branch = "main"
features = ["builder"]

[dependencies.reqwest]
version = "*"
features = ["json", "blocking", "gzip", "brotli", "deflate", "socks"]

[dependencies.tokio]
default-features = false
features = ["macros", "signal", "rt-multi-thread"]
version = "*"
